export const CLIENTS = [
  {
    id: 1,
    userName: "10delin",
    email: "delincruzado20@gmail.com",
    password: "123",
    phone: "695484893",
    address: "Calle Mesón",
    city: "Cadiz",
    state: "Cadiz",
    zip: " 11005",
    country: "Spain",
  },
  {
    id: 2,
    userName: "11pedro",
    email: "pedro11@gmail.com",
    password: "Pedro11",
    phone: "677675889",
    address: "Calle Faros",
    city: "Jerez",
    state: "Cadiz",
    zip: " 11005",
    country: "Spain",
  },
  {
    id: 3,
    userName: "12juan",
    email: "",
    phone: "677675889",
    address: "Calle Faros",
    city: "Jerez",
    state: "Cadiz",
    zip: " 11005",
    country: "Spain",
  },
];
